site_name: ZabbixMan
site_author: Iker Landajuela
theme: readthedocs
repo_url: https://github.com/ikerlandajuela/ZabbixMan/
pages:
    - Inicio: index.md
    - General:
        - 'Descripci贸n general': 'general/descripcion_general.md'
    - Server:
        - 'Instalaci贸n - Ubuntu 16.04 - VBox': 'server/instalacion_ubuntu_vbox.md'
        - 'Diagn贸stico de problemas': 'server/problemas.md'
    - Agente:
        - 'Instalaci贸n: Agente Win7 en VBox': 'agente/win7_vbox/instalacion_agente_win7_vbox.md'